### PR TITLE
feat: added vectorized expectation value computation for a batch of s…

### PR DESCRIPTION
**Pull request by teng10**
This is an implementation of vectorzied fuction to compute expectation values `torchclifford.utils.stabilizer_expect()` for multiple stabilizer states (see UnitaryFund issue [here](https://github.com/hongyehu/PyClifford/issues/15)) using vmap PyTorch.
Currently, the computation is not yet vmapped as the following block raises an error
```
# vmap currently blocked by issue: https://github.com/pytorch/pytorch/issues/103329
# vectorizable_stabilizer_expect_r = functools.partial(vectorizable_stabilizer_expect, r=r) # fix r
# batched_stabilizer_expect = torch.vmap(vectorizable_stabilizer_expect_r, in_dims=(0,0, None, None), out_dims=0)
# return batched_stabilizer_expect(gs_stb_batched, ps_stb_batched, gs_obs, ps_obs)    
```
This is because of a potential issue in PyTorch: https://github.com/pytorch/pytorch/issues/103329

### CODE REVIEW

**Comment by natestemen** [comment]
ping @hongyehu in case you haven't seen this.

**Comment by hongyehu** [comment]
> ping @hongyehu in case you haven't seen this.

Hi Nate! I have seen this PR, and reviewing it. Many thanks!

**Review by hongyehu — APPROVED** [review]
This PR has successfully implemented vectorized expectation value of a batch of Pauli observables for a stabilizer state.

**Comment by hongyehu** [comment]
New implementation of vectorized_batch_expectation, which enables parallel expectation value evaluation for single states. Future thinking: parallelization of states

**Pull request merged**
